name: Check links
on:
  schedule:
    - cron: "0 4 * * SAT"
  workflow_dispatch:
jobs:
  check-links:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: ./.github/actions/setup
        with:
          install-deps: true
      - name: Check links
        run: pnpm run scripts:check-links -- ci
  notify-on-failure:
    needs: check-links
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Send push notification
        run: |
          curl -s \
            --form-string "token=${{ secrets.PUSHOVER_TOKEN }}" \
            --form-string "user=${{ secrets.PUSHOVER_USER }}" \
            --form-string "title=Homepage" \
            --form-string "message=❌ Check links failed" \
            --form-string "url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            https://api.pushover.net/1/messages.json
  notify-on-success:
    needs: check-links
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Send push notification
        run: |
          curl -s \
            --form-string "token=${{ secrets.PUSHOVER_TOKEN }}" \
            --form-string "user=${{ secrets.PUSHOVER_USER }}" \
            --form-string "title=Homepage" \
            --form-string "message=✅ Check links successful" \
            --form-string "url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            https://api.pushover.net/1/messages.json
