name: Setup and test

on:
  workflow_call:
    inputs:
      env:
        description: "Environment to use for testing"
        required: false
        type: string
        default: "test"
      run-checks-and-tests:
        description: "Run checks and tests"
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV: ${{ inputs.env }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
    steps:
      - uses: ./.github/actions/setup
        with:
          install-deps: true
      - name: Build
        run: pnpm run build
  lint-and-format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: inputs.run-checks-and-tests == true
    steps:
      - uses: ./.github/actions/setup
        with:
          install-deps: true
      - name: Lint
        run: pnpm run lint:ci
      - name: Format
        run: pnpm run format:ci
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: inputs.run-checks-and-tests == true
    steps:
      - uses: ./.github/actions/setup
        with:
          install-deps: true
      - name: Test
        run: pnpm run test
        env:
          ENV: test
  playwright:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: inputs.run-checks-and-tests == true
    steps:
      - uses: ./.github/actions/setup
        with:
          install-deps: true
      - name: Install Playwright Browsers
        run: pnpm exec playwright install chromium --only-shell
      - name: Run Playwright tests
        run: pnpm exec playwright test
        env:
          ENV: test
      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
